name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [platform_ops-x64-linux]
        
    steps:
      - uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init

      - name: Configure
        run: cmake --preset ${{ matrix.target }} -DLLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm -DClang_DIR=/usr/lib/llvm-21/lib/cmake/clang

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release

      - name: Test
        run: ctest --preset ${{ matrix.target }} --output-on-failure

  build-windows:
      runs-on: windows-latest
      permissions:
        contents: read
      strategy:
        fail-fast: false
        matrix:
          target: [platform_ops-x64-windows]

      env:
        LLVM_VERSION: 21.1.8 

      steps:
        - uses: actions/checkout@v4

        - uses: ilammy/msvc-dev-cmd@v1

        - name: Update Submodules
          run: git submodule update --init

        - name: Configure
          run: cmake --preset ${{ matrix.target }}

        - name: Build
          run: cmake --build --preset ${{ matrix.target }} --config Release

        - name: Test
          run: ctest --preset ${{ matrix.target }} --output-on-failure